import { Transaction, BudgetLimit } from '../types/budget';

export const DEFAULT_BUDGET_LIMITS: BudgetLimit[] = [
  { category: 'Housing', limit: 1800 },
  { category: 'Food & Dining', limit: 650 },
  { category: 'Utilities & Bills', limit: 350 },
  { category: 'Transportation', limit: 300 },
  { category: 'Entertainment', limit: 250 },
  { category: 'Shopping', limit: 300 },
  { category: 'Health & Fitness', limit: 150 },
  { category: 'Miscellaneous', limit: 200 },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    title: 'Harrison Take-Home Salary Deposit',
    amount: 5200,
    type: 'income',
    category: 'Harrison Monthly Take-Home Pay',
    date: '2026-07-01',
    note: 'Primary salary payout',
  },
  {
    id: 'tx-1b',
    title: 'Camille Take-Home Salary Deposit',
    amount: 4800,
    type: 'income',
    category: 'Camille Monthly Take-Home Pay',
    date: '2026-07-01',
    note: 'Camille monthly paycheck',
  },
  {
    id: 'tx-2',
    title: 'Apartment Rent Payment',
    amount: 1650,
    type: 'expense',
    category: 'Housing',
    date: '2026-07-02',
    note: 'Includes water and trash',
  },
  {
    id: 'tx-3',
    title: 'Weekly Grocery Haul',
    amount: 184.50,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-07-05',
    note: 'Trader Joe\'s & Whole Foods',
  },
  {
    id: 'tx-4',
    title: 'Electric & Power Bill',
    amount: 142.20,
    type: 'expense',
    category: 'Utilities & Bills',
    date: '2026-07-08',
    note: 'Summer air conditioning peak',
  },
  {
    id: 'tx-5',
    title: 'Freelance Design Consultation',
    amount: 850,
    type: 'income',
    category: 'Misc Income',
    date: '2026-07-10',
    note: 'UI mockup deliverables',
  },
  {
    id: 'tx-6',
    title: 'Streaming & Fiber Internet',
    amount: 89.99,
    type: 'expense',
    category: 'Utilities & Bills',
    date: '2026-07-12',
    note: 'Gigabit fiber + Netflix',
  },
  {
    id: 'tx-7',
    title: 'Concert & Night Out',
    amount: 125.00,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-07-15',
    note: 'Tickets + venue drinks',
  },
  {
    id: 'tx-8',
    title: 'Suburban Transit Pass',
    amount: 110.00,
    type: 'expense',
    category: 'Transportation',
    date: '2026-07-18',
    note: 'Monthly commuter pass',
  },
  {
    id: 'tx-9',
    title: 'New Running Shoes & Activewear',
    amount: 145.80,
    type: 'expense',
    category: 'Shopping',
    date: '2026-07-20',
    note: 'Nike clearance sale',
  },
  {
    id: 'tx-10',
    title: 'Gym Membership',
    amount: 65.00,
    type: 'expense',
    category: 'Health & Fitness',
    date: '2026-07-22',
    note: 'Monthly access tier',
  },
  {
    id: 'tx-11',
    title: 'Weekend Dinner with Friends',
    amount: 98.40,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-07-25',
    note: 'Italian bistro & dessert',
  },
  {
    id: 'tx-12',
    title: 'Stock Dividend Payout',
    amount: 215.30,
    type: 'income',
    category: 'Investments',
    date: '2026-07-28',
    note: 'Quarterly index fund dividend',
  },
  {
    id: 'tx-13',
    title: 'Fuel & Car Wash',
    amount: 54.00,
    type: 'expense',
    category: 'Transportation',
    date: '2026-07-30',
    note: 'Chevron premium gas',
  }
];
